default: &default
  adapter: postgresql
  username: jkmcrg
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: chem_id_dev

production:
  <<: *default
  database: chem_id_dev

test:
  <<: *default
  database: chem_id_test
